# Maintainer: Jonas Riedel
#
# This PKGBUILD was generated by `cargo aur`: https://crates.io/crates/cargo-aur

pkgname=rustyfetch-bin
pkgver=0.1.0
pkgrel=1
pkgdesc="Fetch your system information via Rust!"
url="https://github.com/jonasrdl/rustfetch"
license=("AGPL-3.0")
arch=("x86_64")
provides=("rustyfetch")
conflicts=("rustyfetch")
source=("https://github.com/jonasrdl/rustfetch/releases/download/v$pkgver/rustyfetch-$pkgver-x86_64.tar.gz")
sha256sums=("de33a946da3552563b45756ef437a39460d20aab2517c0aa8b224134ef267d46")

package() {
    install -Dm755 rustyfetch -t "$pkgdir/usr/bin"
    install -Dm644 LICENSE "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
}
